name: AutoScheduling

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  AutoScheduling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/upload-artifact@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Script
        run: python main.py -u "${{ secrets.Username }}" -p "${{ secrets.Password }}"
        
      - name: Execute Script
        run: python main.py -u "${{ secrets.Username1 }}" -p "${{ secrets.Password1 }}"

      - name: Upload Log File
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: agendamento.log
